### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by gagipro** [MotherDuck-Open-Source/duckdb-power-query-connector#19]
Hello,

I couln't reproduce any working example, locally or with Motherduck.

thanks

**Comment by guenp** [comment]
@gagipro, which version of the ODBC driver did you use?

**Comment by gagipro** [comment]
> @gagipro, which version of the ODBC driver did you use?

Hello, I just manage to make it work!
Using the 0.10 version like described in your md.
The issue was a badly installed odbc driver, and it happened on two pc.
After removing the registry entries and reinstall it started to work.
Now I'm facing other issues with complex datatypes like map (perhaps also structs).
Do you know if those datatypes could be supported and what's missing either in the odbc driver or the custom connector?
I can open a separate issue if needed.

**Comment by CurtHagenlocher** [comment]
ODBC doesn't have great support for complex data types. There wasn't really any at all until the ODBC 4.0 specification ~8 years ago or so, but this presented a real "chicken-and-egg" problem: no drivers would implement it because no applications supported it, and no applications would implement it because no drivers supported it. And at the end of the day the only real strength of ODBC is its ubiquity, and this ubiquity is due in part to the ODBC 3.0 spec being almost thirty years old (and there being only minor differences in 3.5 and 3.8).

What drivers do instead for complex data types varies from driver to driver, but returning them as JSON of some kind is fairly common.

**Comment by gagipro** [comment]
> ODBC doesn't have great support for complex data types. There wasn't really any at all until the ODBC 4.0 specification ~8 years ago or so, but this presented a real "chicken-and-egg" problem: no drivers would implement it because no applications supported it, and no applications would implement it because no drivers supported it. And at the end of the day the only real strength of ODBC is its ubiquity, and this ubiquity is due in part to the ODBC 3.0 spec being almost thirty years old (and there being only minor differences in 3.5 and 3.8).
> 
> What drivers do instead for complex data types varies from driver to driver, but returning them as JSON of some kind is fairly common.

Thanks for all explanations, this makes more sense to me now.

**Comment by gagipro** [comment]
For those who encounter initial issue, I think it comes from source install folder and bad windows path.
