### ISSUE TITLE
UTF-8 encoded data is not rendered properly

### ISSUE THREAD

**Issue by guenp** [MotherDuck-Open-Source/duckdb-power-query-connector#24]
Related issue: https://github.com/duckdb/duckdb/issues/11386

Here are repro steps:

```
import csv, os
 with open(os.path.expanduser('~/test_utf8.csv'), 'w', newline='', encoding='utf-8') as f:
     writer = csv.writer(f, delimiter=';')
     writer.writerow([u'Ablösung', u'Ásgarðr', u'气功', 1, 2, 3.14])
```

Loading this in Power BI gives:
<img width="631" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/a7a38b7b-44d4-40e4-a237-df3294afd816">

<img width="767" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/31df9bd1-094a-494a-a985-fa0277cb6d73">

**Comment by guenp** [comment]
It looks like Windows is trying to decode the UTF-8 string as UTF-16.

Here is a workaround in Power Query to convert back to UTF-8:

```
let
    Database = "~\test.db",
    MotherDuckToken = "",
    ReadOnly = true,
    OdbcDatasource = DuckDB.Contents(Database, MotherDuckToken, ReadOnly, options),
    ResultTable = OdbcDatasource{[Item="test_utf8"]}[Data],
    columnNames = Table.ColumnNames(ResultTable),
    decodeUtf8 = (value) =>
        if (Type.Is(Value.Type(value), type text)) then
            Text.FromBinary(Text.ToBinary(value, TextEncoding.Windows), TextEncoding.Utf8)
        else
            value,
    decodeUtf8Table = (result) =>
        Table.TransformColumns(ResultTable, List.Transform(columnNames, (col) => {col, each decodeUtf8(_)}))
in
    decodeUtf8Table(ResultTable)
```

**Comment by CurtHagenlocher** [comment]
Officially, the only Unicode encoding that ODBC supports is UCS-2. (This is of course an artifact of the time the spec was created.)

**Comment by guenp** [comment]
I was able to get the text to load by turning on UTF-8 support in the Language & Region settings.
Steps:
1. Open start menu and type "Language settings". Open the "Language & region" settings
2. Click on "Administrative language settings"
3. Click on "Change system locale"
4. Check the "Beta: Use Unicode UTF-8 for worldwide language support" and click OK

![Screenshot 2024-05-03 165950](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/3251d212-0cde-44be-b3a5-68a0d3d434cf)

This prompts Windows to restart.
Next, open Power BI, click on "Options and settings" -> "Options" -> "Data Load" and click the "Clear cache" button.

Now, you should be able to load your UTF-8 encoded database with Power BI directly without using any workarounds:

<img width="653" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/bc83d199-317b-4142-a180-579a9b9d8a05">

**Comment by guenp** [comment]
Thanks @CurtHagenlocher, yeah that makes sense, in general it looks like Windows-1252 is used by default do decode binary strings on Windows. I tried to rewrite the ODBC driver to return UTF-16 instead by converting the UTF-8 to UTF-16 internally before returning it in `SQLGetData` but I couldn't get it to work properly, Windows was still decoding the strings incorrectly. Do you think the above solution is a good workaround for now? I'm on Windows 11 Pro, it's possible this option is not available for all Windows distributions.

**Comment by guenp** [comment]
Closing this issue because I believe it's fixed by updating the Region settings.

**Comment by CurtHagenlocher** [comment]
Sorry for the slow response; I had to do a bit of research to understand the details.

ODBC lets clients bind strings either via SQL_C_CHAR or SQL_C_WCHAR. The latter is probably defined by spec as UCS-2 (though I imagine today it would probably be UTF-16) while the former does not seem to specify a particular text encoding. Power Query always binds as SQL_C_WCHAR -- in part because of this ambiguity, but also because we're going to marshal the data to .NET for which strings are always UTF-16. Now I imagine that the DuckDB ODBC driver probably only supports binding SQL_C_CHAR, so when the ODBC driver manager gets a request to bind SQL_C_WCHAR it will ask the driver for SQL_C_CHAR and then do the conversion in the driver manager using the system code page. That's the reason this configuration change works; it sets the system code page to be UTF-8 so that when the ODBC driver manager calls MultiByteToWideChar for the conversion we end up with the expected result.

Arguably, having to change a system configuration setting to make this scenario work is not a great solution and it may cause other things to break. (This, I think, is why that flag has been marked as "Beta" for the last four years... .) I think the preferable solution would be for the DuckDB ODBC driver to support binding of SQL_C_WCHAR directly instead of using the driver manager. This should in principle be a fairly straightforward change, though I have to admit I've only ever consumed ODBC drivers and never actually written one myself.

**Comment by guenp** [comment]
@CurtHagenlocher No worries, thanks for sharing your thoughts!
I think your recommendation to implement this on the driver level make sense. We may need to think about a good way to make this work for different platforms.
CC @maiadegraaf

**Comment by zenzeinet** [comment]
> It looks like Windows is trying to decode the UTF-8 string as UTF-16.
> 
> Here is a workaround in Power Query to convert back to UTF-8:
> 
> ```
> let
>     Database = "~\test.db",
>     MotherDuckToken = "",
>     ReadOnly = true,
>     OdbcDatasource = DuckDB.Contents(Database, MotherDuckToken, ReadOnly, options),
>     ResultTable = OdbcDatasource{[Item="test_utf8"]}[Data],
>     columnNames = Table.ColumnNames(ResultTable),
>     decodeUtf8 = (value) =>
>         if (Type.Is(Value.Type(value), type text)) then
>             Text.FromBinary(Text.ToBinary(value, TextEncoding.Windows), TextEncoding.Utf8)
>         else
>             value,
>     decodeUtf8Table = (result) =>
>         Table.TransformColumns(ResultTable, List.Transform(columnNames, (col) => {col, each decodeUtf8(_)}))
> in
>     decodeUtf8Table(ResultTable)
> ```

WOW! Works perfectly and solves the issue. I would have never been able to write that PowerQuery code. THANK YOU SO MUCH Guenp FOR SHARING THIS! ♥
