### ISSUE TITLE
Datatypes incorrectly inferred in Power BI

### ISSUE THREAD

**Issue by edwinweber** [MotherDuck-Open-Source/duckdb-power-query-connector#36]
I tested the connection to Power BI with the latest ODBC-driver and DuckDB 1.1.1.

.open edwin_test.db
-- Create the table
CREATE TABLE test_table (
    column1 INTEGER,
    column2 VARCHAR
);
INSERT INTO test_table (column1, column2) VALUES (1, 'something first');
INSERT INTO test_table (column1, column2) VALUES (2, 'something second');
SELECT * FROM test_table;

When I connect to the test_table in Power BI following this method: https://motherduck.com/docs/integrations/bi-tools/powerbi/
the result is that the datatypes are recognized as Whole Number for column1 (correct) and Decimal Number for column2 (incorrect). The preview of the data works, but when loading the data into the model I get the error:
Failed to save modifications to the server. Error returned: 'OLE DB or ODBC error: Type mismatch. (Exception from HRESULT: 0x80020005 (DISP_E_TYPEMISMATCH)).
I can change the datatype myself in Power BI to Text, then it works.

**Comment by guenp** [comment]
Thanks Edwin! I can repro this behavior. I will work on a fix.

**Comment by guenp** [comment]
Looks like this PR changed what types are returned: https://github.com/duckdb/duckdb-odbc/pull/9
We didn't catch this because the Power Query SDK in VS Code (which is what we use for testing) isn't type sensitive (while Power BI is)!
I got rid of the `SQLColumns` override which was converting DuckDB types into SQL types, because this is now no longer needed 🎉 
<img width="299" alt="image" src="https://github.com/user-attachments/assets/ad65699d-1f8b-4ccd-ad7d-867b923eebd3">
Thanks again @edwinweber for catching this and reporting it back to us!

**Comment by guenp** [comment]
@edwinweber I pushed a new release with the fix, you can find the latest .mez connector file here: https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/releases/tag/v0.1.5
